### ISSUE TITLE
generate .tamagui failed

### ISSUE THREAD

**Issue by jasonlewicki** [nderscore/tamagui-typescript-plugin#6]
```node generate-tamagui-json.js

    ➡ [tamagui] built config and components (483ms):

        Config     ./.tamagui/tamagui.config.cjs
        Components ./.tamagui/tamagui-components.config.cjs


⚠️ Tamagui Warning [001]: Skipping loading /expo/.tamagui/tamagui.config.cjs due to error bundling.
   - message: Cannot access 'View' before initialization
   - for more info see: https://tamagui.dev/docs/intro/errors#warning-001
   - set TAMAGUI_SHOW_FULL_BUNDLE_ERRORS=1 to see stack trace


babel err ReferenceError: Cannot access 'View' before initialization
    at Object.View (/expo/node_modules/@tamagui/static/node_modules/@tamagui/core/dist/cjs/index.js:19:15)
    at Object.get (/expo/node_modules/@tamagui/static/node_modules/@tamagui/core/dist/cjs/index.js:11:88)
    at Object.<anonymous> (/expo/node_modules/@tamagui/static/node_modules/@tamagui/core/dist/cjs/index.js:25:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._compile (/expo/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at newLoader (/expo/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.newLoader (/expo/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/expo/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

⚠️ Tamagui Warning [001]: Skipping loading /expo/.tamagui/tamagui-components.config.cjs due to error bundling.
   - message: Cannot access 'View' before initialization
   - for more info see: https://tamagui.dev/docs/intro/errors#warning-001
   - set TAMAGUI_SHOW_FULL_BUNDLE_ERRORS=1 to see stack trace


/expo/node_modules/@tamagui/static/node_modules/@tamagui/simple-hash/dist/cjs/index.js:24
  const len = str.length;
                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at simpleHash (/expo/node_modules/@tamagui/static/node_modules/@tamagui/simple-hash/dist/cjs/index.js:24:19)
    at createCSSVariable (/expo/node_modules/@tamagui/static/node_modules/@tamagui/web/src/createVariable.ts:92:16)
    at variableToCSS (/expo/node_modules/@tamagui/static/node_modules/@tamagui/web/src/helpers/registerCSSVariable.ts:9:15)
    at <anonymous> (/expo/node_modules/@tamagui/static/node_modules/@tamagui/web/src/createTamagui.ts:137:31)
    at createTamagui (/expo/node_modules/@tamagui/static/node_modules/@tamagui/web/src/createTamagui.ts:205:3)
    at loadTamagui (/expo/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:50:107)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```

**Comment by nderscore** [comment]
Is this from the expo-only workaround script?

Can you confirm that all your `@tamagui/...` packages are on the same version, and if that's not the issue, can you post some details about how to reproduce it?

**Comment by jasonlewicki** [comment]
Yeah expo-only script. 

This is in a monorepo with no base.tsconfig.js

```
 System:
    OS: macOS 14.1.2
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1011.51 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.21 - ~/Repositories/.../node_modules/.bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.12.04.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 101.1.38.115
    Chrome: 120.0.6099.109
    Safari: 17.1.2
  npmPackages:
    @babel/core: ^7.20.0 => 7.23.6
    @expo/webpack-config: ^19.0.0 => 19.0.0
    @nderscore/tamagui-typescript-plugin: ^0.6.0 => 0.6.0
    @tamagui/cli: ^1.79.13 => 1.79.13
    @tamagui/config: ^1.79.13 => 1.79.13
    @tamagui/static: ^1.79.15 => 1.79.15
    @tamagui/theme-builder: ^1.79.13 => 1.79.13
    @trpc/client: ^10.44.1 => 10.44.1
    @types/react: ~18.2.14 => 18.2.45
    expo: ^49.0.21 => 49.0.21
    expo-constants: ~14.4.2 => 14.4.2
    expo-dev-client: ~2.4.12 => 2.4.12
    expo-font: ~11.4.0 => 11.4.0
    expo-linking: ~5.0.2 => 5.0.2
    expo-router: ^2.0.0 => 2.0.14
    expo-splash-screen: ~0.20.5 => 0.20.5
    expo-sqlite: ~11.3.3 => 11.3.3
    expo-status-bar: ~1.6.0 => 1.6.0
    expo-system-ui: ~2.4.0 => 2.4.0
    prettier: ^3.1.1 => 3.1.1
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-native: 0.72.6 => 0.72.6
    react-native-gesture-handler: ~2.12.0 => 2.12.1
    react-native-safe-area-context: 4.6.3 => 4.6.3
    react-native-screens: ~3.22.0 => 3.22.1
    react-native-web: ~0.19.6 => 0.19.9
    tamagui: ^1.79.13 => 1.79.13
    typescript: ^5.1.3 => 5.3.3
```


Ran these scripts:
`npx expo install @nderscore/tamagui-typescript-plugin`

tsconfig looks like this:
```
{
  "compilerOptions": {
    "paths": {
...
    },
  },
  "plugins": [
    {
      "name": "@nderscore/tamagui-typescript-plugin",
      // all settings are optional, the defaults are shown below as an example:
      //
      // relative or absolute path to a tamagui app (parent folder of .tamagui)
      "pathToApp": "./",
      //
      // the default theme to show for theme tokens when inlined
      "defaultTheme": "light",
      //
      // the size (in pixels) of color tiles in previews
      "colorTileSize": 18,
      //
      // set false to hide translations for shorthand properties
      "showShorthandTranslations": true,
      //
      // options for filtering autocomplete suggestions
      "completionFilters": {
        //
        // set false to hide non-theme color tokens
        "showColorTokens": true,
        //
        // set false to hide $true and $-true tokens from all scales
        "showTrueTokens": true,
        //
        // per-scale lists of specific token names to exclude from autocomplete results
        "custom": {
          // "themeColor": [],
          // "color": [],
          // "size": [],
          // "space": [],
          // "radius": [],
          // "zIndex": []
        }
      }
    }
  ],
  "extends": "expo/tsconfig.base",
}
```

Then went through the expo-only steps, ending with:
`node generate-tamagui-json.js`

**Comment by jasonlewicki** [comment]
You were right, changed the static package to .13
