### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by yngfoxx** [nderscore/tamagui-typescript-plugin#7]
Hello

Firstly I would like to appreciate the people who have put their time and energy to create this plugin for free.

I am new to Tamagui and the experience so far has been frustrating especially when trying to setup autocomplete like Nativebase, I have followed the instructions from the README.md but to no avail the autocomplete refuses to activate and the prop values are typed as `any`

![image](https://github.com/nderscore/tamagui-typescript-plugin/assets/47150226/20dfecf8-32fd-464e-8d85-0669b465670a)

and while typing there is no autocomplete.

I am using React-Native + Expo (And Expo Router)

### Packages
"expo": "~49.0.21",
"react-native": "0.72.6",
"expo-router": "2.0.14",

### tsconfig.json
```
{
    "strict": true,
    "extends": "expo/tsconfig.base",
    "compilerOptions": {
        "target": "es6",
        "module": "esnext",
        "baseUrl": "./",
        "paths": {
            "@/*": [ "./*" ],
            "@app/*": [ "./src/*" ],
        },
        "plugins": [
            {
                "name": "@nderscore/tamagui-typescript-plugin",
                "pathToApp": ".",
                "defaultTheme": "dark",
                "colorTileSize": 18,
                "showShorthandTranslations": true,
                "completionFilters": {
                    "showColorTokens": true,
                    "showTrueTokens": true
                }
            }
        ],
        "typeRoots": [
            "expo-router/ts-declarations"
        ]
    }
}
```

### File structure
![image](https://github.com/nderscore/tamagui-typescript-plugin/assets/47150226/8883a38f-dc25-469a-866e-be7b409ea29d)

**Comment by nderscore** [comment]
> prop values are typed as `any` and while typing there is no autocomplete.

Were they typed correctly and was autocomplete working prior to installing the plugin? 

If not, there might be some other Tamagui config that you're missing, such as the [typescript module overrides](https://tamagui.dev/docs/core/configuration#quick-start) (`declare module 'tamagui' { interface TamaguiCustomConfig extends AppConfig {} }`)

If everything is working as expected without the plugin, you can follow these debugging steps for the typescript plugin:

## Confirm that the plugin is being loaded

1. Open the VSCode command palette, find and choose the `Typescript: Open TS Server Log` option. It will probably require reloading the TS server to enable logging.
2. Search the log for a log line containing the following text: `Loading @nderscore/tamagui-typescript-plugin from`

If you don't see this message, the plugin is not being loaded. Your VSCode might not be using the workspace's typescript version, or there is an issue with the tsconfig (it doesn't look like the tsconfig is the issue here though)

## Check the plugin's logs

If the plugin is being loaded, but isn't working, the plugin itself should make entries in the log that start with this text: 

`TSTamagui::`

There might be some information in those logs that could help debug the issue.

**Comment by yngfoxx** [comment]
Hello @nderscore ,

Thanks for the comment, here is what I found in the tsserver.log

```
Info 29   [16:25:42.668] Failed to load module '@nderscore/tamagui-typescript-plugin' from c:/Users/Account/.vscode/extensions/ms-vscode.vscode-typescript-next-5.4.20231226/node_modules/node_modules:
  Error: Could not resolve JS module '@nderscore/tamagui-typescript-plugin' starting at 'c:/Users/Account/.vscode/extensions/ms-vscode.vscode-typescript-next-5.4.20231226/node_modules/node_modules'.
  Looked in:
  c:/Users/Account/.vscode/extensions/ms-vscode.vscode-typescript-next-5.4.20231226/node_modules/@nderscore/tamagui-typescript-plugin/package.json,
  c:/Users/Account/.vscode/extensions/ms-vscode.vscode-typescript-next-5.4.20231226/node_modules/@nderscore/tamagui-typescript-plugin.js,
  c:/Users/Account/.vscode/extensions/ms-vscode.vscode-typescript-next-5.4.20231226/node_modules/@nderscore/tamagui-typescript-plugin.jsx,
  c:/Users/Account/.vscode/extensions/ms-vscode.vscode-typescript-next-5.4.20231226/node_modules/@nderscore/tamagui-typescript-plugin/index.js,
  c:/Users/Account/.vscode/extensions/ms-vscode.vscode-typescript-next-5.4.20231226/node_modules/@nderscore/tamagui-typescript-plugin/index.jsx,
  c:/Users/Account/.vscode/extensions/node_modules/@nderscore/tamagui-typescript-plugin/package.json,
  c:/Users/Account/.vscode/extensions/node_modules/@nderscore/tamagui-typescript-plugin.js,
  c:/Users/Account/.vscode/extensions/node_modules/@nderscore/tamagui-typescript-plugin.jsx,
  c:/Users/Account/.vscode/extensions/node_modules/@nderscore/tamagui-typescript-plugin/index.js,
  c:/Users/Account/.vscode/extensions/node_modules/@nderscore/tamagui-typescript-plugin/index.jsx,
  c:/Users/Account/.vscode/node_modules/@nderscore/tamagui-typescript-plugin/package.json,
  c:/Users/Account/.vscode/node_modules/@nderscore/tamagui-typescript-plugin.js,
  c:/Users/Account/.vscode/node_modules/@nderscore/tamagui-typescript-plugin.jsx,
  c:/Users/Account/.vscode/node_modules/@nderscore/tamagui-typescript-plugin/index.js,
  c:/Users/Account/.vscode/node_modules/@nderscore/tamagui-typescript-plugin/index.jsx,
  c:/Users/Account/node_modules/@nderscore/tamagui-typescript-plugin/package.json,
  c:/Users/Account/node_modules/@nderscore/tamagui-typescript-plugin.js,
  c:/Users/Account/node_modules/@nderscore/tamagui-typescript-plugin.jsx,
  c:/Users/Account/node_modules/@nderscore/tamagui-typescript-plugin/index.js,
  c:/Users/Account/node_modules/@nderscore/tamagui-typescript-plugin/index.jsx,
  c:/Users/node_modules/@nderscore/tamagui-typescript-plugin/package.json,
  c:/Users/node_modules/@nderscore/tamagui-typescript-plugin.js,
  c:/Users/node_modules/@nderscore/tamagui-typescript-plugin.jsx,
  c:/Users/node_modules/@nderscore/tamagui-typescript-plugin/index.js,
  c:/Users/node_modules/@nderscore/tamagui-typescript-plugin/index.jsx,
  c:/node_modules/@nderscore/tamagui-typescript-plugin/package.json,
  c:/node_modules/@nderscore/tamagui-typescript-plugin.js,
  c:/node_modules/@nderscore/tamagui-typescript-plugin.jsx,
  c:/node_modules/@nderscore/tamagui-typescript-plugin/index.js,
  c:/node_modules/@nderscore/tamagui-typescript-plugin/index.jsx
    at resolveJSModule (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:42677:11)
    at Object.require (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:8520:30)
    at _Project.importServicePluginSync (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:177884:27)
    at _ProjectService.requestEnablePlugin (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:183205:16)
    at ConfiguredProject2.enablePlugin (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:179167:25)
    at ConfiguredProject2.enablePluginsWithOptions (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:179875:14)
    at _ProjectService.loadConfiguredProject (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:181600:13)
    at _ProjectService.createAndLoadConfiguredProject (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:181551:10)
    at _ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:181556:26)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:182654:26)
    at c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:182934:64
    at flatMap (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:2608:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:182934:24)
    at updateOpen (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:184136:29)
    at c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:186744:69
    at IpcIOSession.executeWithRequestId (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:186736:14)
    at IpcIOSession.executeCommand (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:186744:29)
    at IpcIOSession.onMessage (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:186786:51)
    at process.<anonymous> (c:\Users\Account\.vscode\extensions\ms-vscode.vscode-typescript-next-5.4.20231226\node_modules\typescript\lib\tsserver.js:188395:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Info 30   [16:25:42.669] Couldn't find @nderscore/tamagui-typescript-plugin
```

Does this mean I have to install the plugin globally instead of into my project?

**Comment by nderscore** [comment]
It looks like your VScode might not be using the workspace's typescript version.

Can you confirm if you followed this install step?

> Make sure your VSCode is configured to use typescript from your workspace:
>
> Open VSCode Command Palette -> Select Typescript Version... -> Use Workspace Version

**Comment by yngfoxx** [comment]
It seems that was it, my bad
the option was not coming up earlier instead it was the select file language that came up so I must have mixed it up
